### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by unilight** [unilight/jatts#1]
Datasets
- [x] JSUT
- [x] JVS
- [x] Hi-Fi-Captain
- [ ] CSJ
- [ ] Emilia-YODAS jp

Models
- [x] FastSpeech 2 (w/ julius forced alignment) + Hi-Fi GAN / PWG
- [ ] VITS w/ mel output (i.e., w/o GAN) + Hi-Fi GAN / PWG
- [x] Matcha-TTS w/ julius forced alignment + Hi-Fi GAN / PWG
- [x] Matcha-TTS w/ MAS + Hi-Fi GAN / PWG
- [ ] VALL-E
- [ ] E2-TTS

Refactor
- Apply accelerate to every recipe?
  - Applied recipes:
    - [x] `egs/hificaptain_jp_female/tts2`
    - [x] `egs/hificaptain_jp_female/tts3`

|             | JSUT | JVS | Hi-Fi Captain | CSJ | Emilia-YODAS jp | 
| ----------- | ---- | --- | ------------- | --- | --- |
| FastSpeech2 |  2025/1/30    |  2025/1/24   |    2025/2/3           | N/A | N/A |
| VITS        |   2025/4/15   |     |       2025/4/15        | N/A | N/A |
| MatchaTTS w/ julius forced alignment  |   2025/2/12   |  2025/2/12   |     2025/2/12          | N/A | N/A |
| MatchaTTS w/ MAS        |  2025/4/10    |  2025/4/15   |       2025/4/10        | N/A | N/A |
| VALL-E      |      |     |      2025/4/18         |  |  |
| E2-TTS      |      |     |      2025/4/15 (basically fails)         |  |  |
